const temas = [
    'Suma de dos numeros',
    'Par o impar',
    'Area del triangulo',
    'Celcius a Fahrenheit',
    'De pesos a dolares',
    'Cajero Automatico',
    'Ciclos',
    'Factorial',
    'Listas',
    'Tabla de multiplicar',
    'Arreglos',
    'Cajero con arreglo',
    'Funciones',
    'Arreglos 2',
    'Calcular promedio',
    'Calificaciones',
    'Palindromo',
]
